#!/bin/bash
## BEGIN INIT INFO
# Provides: firstboot
# Default-Start: 3 5
# Default-Stop: 0 1 2 4 6
# Required-Start:
# Should-Start: $network
# Short-Description: Starts the firstboot configuration program
# Description: Firstboot runs the first time a machine is booted after
#              installation.  It checks for the existance of an
#              /etc/sysconfig/firstboot file.  If the file exists and
#              contains RUN_FIRSTBOOT=NO, firstboot will not run.  Otherwise
#              firstboot will be run.  If /etc/reconfigSys exists or if
#              "reconfig" is provided in the kernel boot arguments,
#              firstboot will run in reconfiguration mode.
## END INIT INFO

#
# firstboot: Starts the firstboot druid if it hasn't been run before
#
# chkconfig: 35 99 95
#
# description: Firstboot is a druid style program that runs on the first \
#              time a machine is booted after install.  It checks for \
#              the existence of an /etc/sysconfig/firstboot file.  If \
#              the file exists and contains RUN_FIRSTBOOT=NO, firstboot \
#              will not run.  Otherwise, firstboot will be run.  \
#              If /etc/reconfigSys exists or if "reconfig" is provided \
#              in the kernel boot arguments, firstboot will run in \
#              reconfiguration mode.
#

# Source function library.
. /etc/init.d/functions

FILENAME=/etc/sysconfig/firstboot

[ -z "$HOME" ] && export HOME=/

case "$1" in
    start)
        args=""

        if [ -f $FILENAME ] && [ ! -z "$(grep 'RUN_FIRSTBOOT=NO' $FILENAME)" ]; then
            exit 0
        fi

        if grep -i "reconfig" /proc/cmdline >/dev/null || [ -f /etc/reconfigSys ]; then
            args="--reconfig"
        fi

        . /etc/sysconfig/i18n

        /usr/bin/plymouth --hide-splash

        /usr/sbin/firstboot $args
        RETVAL=$?

        /usr/bin/plymouth --show-splash

        # If firstboot succeeded, chkconfig it off so we don't see the message
        # every time about starting up firstboot.
        if [ "$RETVAL" -eq 0 ]; then
            action "" /bin/true
            /sbin/chkconfig firstboot off
        else
            action "" /bin/false
        fi

        exit $RETVAL
        ;;

    stop)
        exit 0
        ;;

    *)
        echo $"Usage: $0 {start|stop}"
        exit 2
        ;;
esac
