#! /usr/bin/env python

#
# firstboot
#
# Copyright (C) 2011  Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Red Hat Author(s):  Martin Gracik <mgracik@redhat.com>
#

import optparse
import os
import sys
import tempfile
import traceback

import firstboot.frontend
import firstboot.loader

from firstboot.constants import *

# XXX
from firstboot.config import *

import meh
import meh.handler
import meh.dump


def exception_handler(type, value, tb):
    fd, path = tempfile.mkstemp(prefix='firstboot-', suffix='.trace')
    fo = os.fdopen(fd, 'w')
    traceback.print_exception(type, value, tb, None, fo)
    fo.close()

sys.excepthook = exception_handler


if __name__ == '__main__':

    # only root can do this
    if not os.geteuid() == 0:
        print >> sys.stderr, 'only root can do this'
        sys.exit(1)

    parser = optparse.OptionParser()
    parser.add_option('-m', '--moduledir', dest='module_dir')
    parser.add_option('-r', '--reconfig',
                      action='store_true', default=False)
    parser.add_option('-s', '--autoscreenshot',
                      action='store_true', default=False)
    parser.add_option('-t', '--test',
                      action='store_true', default=False)
    parser.add_option('--themedir', dest='theme_dir')

    opts, args = parser.parse_args()

    # XXX should we run?
    if os.path.isfile('/etc/sysconfig/firstboot'):
        with open('/etc/sysconfig/firstboot') as fobj:
            for line in fobj:
                if line.strip() == 'RUN_FIRSTBOOT=NO':
                    os.system('systemctl stop firstboot-graphical.service > /dev/null 2>&1')
                    os.system('systemctl stop firstboot-text.service > /dev/null 2>&1')
                    sys.exit(0)

    if not opts.module_dir:
        opts.module_dir = MODULE_DIR

    if not opts.theme_dir:
        themes = [d for d in os.listdir(THEME_DIR) if d != 'default']
        if themes:
            opts.theme_dir = os.path.join(THEME_DIR, themes[0])
        else:
            opts.theme_dir = os.path.join(THEME_DIR, 'default')

    # XXX set the theme dir in config
    config.themeDir = opts.theme_dir

    frontend = None
    if 'DISPLAY' not in os.environ:
        frontend = firstboot.frontend.Frontend()
        frontend.set_lang()
        frontend.startx()
        frontend.init_gtk()
        frontend.start_wm()
        frontend.merge_xres()

    # these modules import gtk, so we need to have a display first
    import firstboot.interface
    import meh.ui.gui

    # XXX set up the interface
    config.frontend = frontend
    config.interface = firstboot.interface.Interface(opts.autoscreenshot,
                                                     opts.test)

    # XXX set up meh
    handler_conf = meh.Config(programName='firstboot',
                              programVersion='@VERSION@')
    handler = meh.handler.ExceptionHandler(handler_conf,
                                           meh.ui.gui.GraphicalIntf(),
                                           meh.dump.ExceptionDump)
    handler.install(config)

    # load modules
    loader = firstboot.loader.Loader()
    modules = loader.load_modules(module_dir=opts.module_dir,
                                  reconfig=opts.reconfig)

    if not modules:
        err = 'no modules found'
        raise RuntimeError(err)

    # TODO rewrite the interface
    config.interface.moduleList = modules
    config.interface.createMainWindow()
    config.interface.createScreens()
    config.interface.createSidebar()
    config.interface.run()

    if frontend is not None:
        frontend.kill()

    if not opts.test:
        with open('/etc/sysconfig/firstboot', 'w') as f:
            f.write('RUN_FIRSTBOOT=NO\n')

        if opts.reconfig:
            try:
                os.unlink('/etc/reconfigSys')
            except OSError:
                pass
