#!/usr/bin/python2.2

import sys
import os
import string
import signal
import time

sys.path.append("/usr/share/firstboot")

x_class = None
wm_pid = None
doDebug = None
doReconfig = None
FILENAME = "/etc/sysconfig/firstboot"

for arg in sys.argv:
    if arg == '--reconfig':
        print "starting reconfig mode"
        doReconfig = 1
    if arg == '--debug':
        print "starting with debugging options"
        doDebug = 1

if __name__ == "__main__":
    signal.signal (signal.SIGINT, signal.SIG_DFL)


def startWindowManager():    
    wm_pid = os.fork()

    if (not wm_pid):
        path = '/usr/bin/metacity'
        args = ['--display=:1']
        os.execv(path, args)


    # give time for the window manager to start up
    time.sleep (3)
    status = 0
    try:
        pid, status = os.waitpid (wm_pid, os.WNOHANG)
        
    except OSError, (errno, msg):
        print "in except"
        print __name__, "waitpid:", msg


    if status:
        raise RuntimeError, "Window manager failed to start"

    return wm_pid
def setRootBackground():
    root_pid = os.fork()

    if (not root_pid):
        path = '/usr/bin/X11/xsetroot'
        args = [path, '-solid', 'midnightblue']
        os.execv(path, args)


#Let's check to see if firstboot should be run or not
#If we're in debug mode, run anyway.  Even if the file exists
if (not doDebug):
    #We're not in debug mode, so do some checking
    #First, look and see if /etc/sysconfig/firstboot exists
    try:
        os.stat (FILENAME)

        fd = open(FILENAME, 'r')
        lines = fd.readlines()
        fd.close()

        #If /etc/sysconfig/firstboot exists, see if the value of /etc/redhat-release has been changed.
        #If so, then they must have upgraded, so run firstboot again.
        for line in lines:            
            line = string.strip(line)
            if (string.find(line, "RUN_FIRSTBOOT") > -1) and line[0] != "#":
                if string.find(line, "="):
                    key, value = string.split(line, "=")
                    if value == "NO":
                        #Firstboot should not be run
                        os._exit(0)
                    
    except:
        #Firstboot has never been run before, so start it up
        pass

    #Let's see if /etc/reconfigSys exists.  If it does, we need to enter reconfig mode
    try:	
        os.stat("/etc/reconfigSys")
        #It exists, so set reconfig mode flag to 1
        doReconfig = 1
    except:
        #It doesn't exist, so set reconfig mode flag to 0
        doReconfig = 0

#If there's no X Server running, let's start one
if not os.environ.has_key('DISPLAY'):
    import xserver
    
    try:        
        if os.access("/etc/X11/XF86Config", os.R_OK) or os.access("/etc/X11/XF86Config-4", os.R_OK):
            x_class = xserver.XServer()
    except:
        pass
    
    wm_pid = startWindowManager()
    setRootBackground()


import firstbootWindow
firstbootWindow.firstbootWindow(wm_pid, doReconfig, doDebug)



